//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitTrade.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CoinID { get; set; }
        public decimal CoinCount { get; set; }
        public string CurrencyType { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DateOfPurcahse { get; set; }
    
        public virtual Coin Coin { get; set; }
        public virtual User User { get; set; }
    }
}
